name: attendance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.5.0
  geolocator: ^14.0.2
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  location: ^8.0.1
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
